### ISSUE TITLE
Allow to set the name of the custom coredns configmap

### ISSUE THREAD

**Issue by kubicgruenfeld** [submariner-io/submariner-operator#1166]
**What would you like to be added**:

The ability to set the name of the custom configmap to coredns.

**Why is this needed**:

Similar to #1054, in our environment we can provide custom configmaps to coredns in kube-system but the name of the configmap must be coredns-extra-configs. Currently we have to deploy this manually:

```
apiVersion: v1
data:
  Corefile: |
    clusterset.local:53 {
        forward . <<lighthouse-coredns-clusterip>>
    }
kind: ConfigMap
metadata:
  name: coredns-extra-configs
  namespace: kube-system
```

It would be nice to have this deployed by the operator. Would also really aprecciate to have this backported to 0.8.1.
