### ISSUE TITLE
Allow subctl/operator --loadbalancer mode

### ISSUE THREAD

**Issue by mangelajo** [submariner-io/submariner-operator#1387]
Related to: https://github.com/submariner-io/submariner/issues/1071

Add a setting to the operator and subctl to enable load-balancer mode. 
Once enabled creates the LoadBalancer automatically in the submariner-operator namespace.

Investigate all annotations necessary on clouds to use UDP loadbalancers,  an example for AWS:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: gw1
  namespace: submariner-operator
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: submariner-gateway
    gateway: active
  ports:
    - name: ipsec-encap
      protocol: UDP
      port: 4500
      targetPort: 4500
    - name: natt-discovery
      protocol: UDP
      port: 4490
      targetPort: 4490
  type: LoadBalancer

```
