### ISSUE TITLE
Allow K8s < 1.17 but disable Lighthouse

### ISSUE THREAD

**Issue by skitt** [submariner-io/submariner-operator#1399]
See https://github.com/submariner-io/submariner/issues/1374 for context. `subctl` requires K8s 1.17, but that’s currently only needed for Lighthouse. Perhaps we could allow installing Submariner on pre-1.17 clusters, but disable Lighthouse.

**Comment by huxiaoliang** [comment]
@skitt do you have any plan to support Lighthouse works on pre-1.17 clusters?  Since many k8s cluster at IDC and Cloud still state in pre-1.17

**Comment by aswinsuryan** [comment]
The Endpointslice should be the only missing dependency in 1.17. Installing it manually should resolve it. You could try installing below and see if the lighthouse is working fine.

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: endpointslices.discovery.k8s.io
spec:
  group: discovery.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: EndpointSlice
    plural: endpointslices
    singular: endpointslice
```
